### ISSUE TITLE
Develop for EX2 ultra

### ISSUE THREAD

**Issue by Serferman** [Czuz/mySync-for-myCloud-OS5#11]
Hello, I would like to develop apps for EX2 Ultra, but I don't know how, I have read a lot and I don't know how to develop any app. Could you guide me or teach me how to develop them correctly?

I'm sorry if I have disturbed you

**Comment by Czuz** [comment]
Hi,

First of all, check community forum: https://community.wd.com/c/os5/developer-apps/276

You will find 
[https://community.wd.com/t/sdk-for-os-5/265122](App Guide) there alongside necessary packaging tool (mkapkg).
