### ISSUE TITLE
Install failed on MyCloudEX2Ultra

### ISSUE THREAD

**Issue by davyzhen** [Czuz/mySync-for-myCloud-OS5#12]
I downloaded the most recent MyCloudEX2Ultra_mySync_1.1.5-rc1.bin file and attempted to install it manually. However, I received the following error message: "App Installation Failed. Unable to upload the app package for installation. Please verify your network connection and try the installation again."

**Comment by Czuz** [comment]
Hi.

Sorry, to hear that.

As per disclaimer on the release page - I haven't had access to this hardware to test the package. I'll check, how can we troubleshoot that.

**Comment by Czuz** [comment]
1) please confirm exact model of your NAS.
2) provide Firmware version (can be checked on the main dashboard after login to myCloud).
3) check if there are any logs related to failed installation in Settings -> Utilities -> System Logs (if not try again with Extended Logging enabled)

Are you familiar with Linux shell?

**Comment by davyzhen** [comment]
Model: My Cloud EX2 Ultra
Firmware: 5.27.157
No logs (I enabled Extended Logging)

**Comment by Czuz** [comment]
Hi,

Thank you for patientce.

I'd like you to verifiy few things by logging in to the NAS with SSH.

1. Enable SSH on your NAS
`Settings -> Network -> SSH -> ON` - on first activation setup a password

I recommend to turn it off as soon as you end your session.

2. Login to the machine.
- on Linux / MacOS use following command from terminal:
`ssh ssh@<ip-address-of-you-NAS>`
-  on Windows you can use [PuTTY](https://www.chiark.greenend.org.uk/~sgtatham/putty/).

3. Try to install the package from web User Interface

4. Execute following command and paste resut here:
```
cd /mnt/HD/HD_a2/Nas_Prog/
ls -la | grep mySync
cd /mnt/HD/HD_a2/.systemfile/
ls -la | grep mySync
cd /var/www/apps/
ls -la | grep mySync
cat /var/log/analyticpublic.log | grep mySync
```
5. Check `Settings -> Utilities -> System Logs`
6. Turn off SSH
`Settings -> Network -> SSH -> OFF`

**Comment by athos99** [comment]
Hello, i have a MyCloudEX2Ultra and I have the same problem.

When I generate the package :
`

user@acerswiftgo:~/www/mySync-for-myCloud-OS5/mySync$ ./mksapkg -E -s -m MyCloudEX2Ultra
============================================
        mksapkg version: 2.0
============================================
MinFWVer: [5.0.0]
MaxFWVer: []
*** WARNING : deprecated key derivation used.
Using -iter or -pbkdf2 would be better.
Error setting cipher BF-CBC
40F7A239357F0000:error:0308010C:digital envelope routines:inner_evp_generic_fetch:unsupported:../crypto/evp/evp_fetch.c:349:Global default library context, Algorithm (BF-CBC : 11), Properties ()
mySync/
mySync/web/
mySync/web/AuthChecker.php
mySync/web/mySync.png
mySync/web/RemotesConfiguration.php
mySync/web/index.html
mySync/web/mySync.js
mySync/web/ConfigurationManager.php
mySync/web/LogFile.php
mySync/web/mySync.css
mySync/web/LogViewer.php
mySync/stop.sh
mySync/log/
mySync/log/.gitkeep
mySync/preinst.sh
mySync/clean.sh
mySync/apkg.sign
mySync/apkg.xml
mySync/mksapkg
mySync/install.sh
mySync/bin/
mySync/bin/README.html
mySync/bin/my_sync_guardian.sh
mySync/bin/my_sync_deamon.sh
mySync/bin/git-log.txt
mySync/bin/README.txt
mySync/bin/rclone
mySync/bin/rclone.1
mySync/bin/my_sync_deamon.conf
mySync/apkg.rc
mySync/etc/
mySync/etc/.gitkeep
mySync/remove.sh
mySync/init.sh
mySync/start.sh
***[../MyCloudEX2Ultra_mySync_1.1.7.bin(03072024)]

NAS type:               MyCloudEX2Ultra
module name:            mySync
module versioin:        1.1.7
packager:               Czuz

header length:          19582048
header checksum:        532823AB

Add-ons "../MyCloudEX2Ultra_mySync_1.1.7.bin(03072024)" create!

user@acerswiftgo:~/www/mySync-for-myCloud-OS5/mySync$
`


When I install the package a popup error display :

App Installation Failed. Unable to upload the app package for installation. Please verify your network connection and try the installation again."

PS: I have installed with success the package rclone form projetc https://github.com/WDCommunity/wdpksrc/tree/master/wdpk/rclone

**Comment by Czuz** [comment]
Hi @athos99 ,

I can see that you have built a package by yourself.

If I prepare a branch with additional debug instructions during the weekend, would you try to deploy it?

Kind regards,
Czuz

**Comment by athos99** [comment]
It's ok now. Your code is good !
The pèroblem come frome my environement, maybe the package signature was wrong.

My solution, i use the docker image of https://github.com/WDCommunity/wdpksrc

**Comment by turnkit** [comment]
I'm having the same error when uploading to two different PR4100's on OS5 (using the PR4100 build)

I'm not sure how to build it myself.  Can you list step-by-step instructions?


BusyBox v1.30.1 (2023-01-16 13:49:52 UTC) built-in shell (ash)
Enter 'help' for a list of built-in commands.

root@LibraryArchives ~ # pwd
/home/root
root@LibraryArchives ~ # cd /mnt/HD/HD_a2/Nas_Prog/
root@LibraryArchives Nas_Prog # ls -la
drwxrwxrwx    3 root     root          4096 May 26 07:29 .
drwxrwxrwx   12 root     root          4096 May 25 02:45 ..
drwxrwxrwx    3 root     root          4096 May 26 07:30 _install
root@LibraryArchives Nas_Prog # ls -la | grep mySync
root@LibraryArchives Nas_Prog # cd /mnt/HD/HD_a2/.systemfile/
root@LibraryArchives .systemfile # ls -la | grep mySync
root@LibraryArchives .systemfile # cd /var/www/apps/
root@LibraryArchives apps # ls -la | grep mySync
root@LibraryArchives apps # cat /var/log/analyticpublic.log | grep mySync
root@LibraryArchives apps #

**Comment by turnkit** [comment]
MyCloudPR4100_mySync_1.1.8.bin

App Installation Failed
Unable to upload app package for installation. Please check your network connection and try again

**Comment by turnkit** [comment]
If I just copy the .bin file and run it from the shell I get the following.  I'm sure this is not the right way to invoke it but I'm desperate to try something since backing up 40 TB from one NAS to another THROUGH WINDOWS is too slow!

root@LibraryArchives ~ # cp /mnt/HD/HD_a2/movietime_big/MyCloudPR4100_mySync_1.1.8.bin .
root@LibraryArchives ~ # chmod +x MyCloudPR4100_mySync_1.1.8.bin
root@LibraryArchives ~ # ./MyCloudPR4100_mySync_1.1.8.bin
./MyCloudPR4100_mySync_1.1.8.bin: line 1: BlackCyZmySync1.1.8: not found
./MyCloudPR4100_mySync_1.1.8.bin: line 2: syntax error: unexpected ")"

**Comment by turnkit** [comment]
I also tried modifying the apps folder .json file to add the app to the menu of available apps but the pre-populated list seems to revert to the original as soon as I refresh the apps page.

**Comment by turnkit** [comment]
Would adding the app as in their list be a workaround somehow?

https://community.wd.com/t/my-cloud-os5-app-template/286542

**Comment by Czuz** [comment]
Hi,

In order to build it by yourself you need to follow this [instruction.](https://github.com/Czuz/mySync-for-myCloud-OS5?tab=readme-ov-file#how-to-build-package-from-sources).

The link, that you provided contains the mkspag tool required to build the "bin" file:
https://community.wd.com/t/my-cloud-os5-app-template/286542

It contains also a PDF with instructions how to execute installation / startup scripts manually.

Let me check rest of the provided information.

P.S. The "bin" file is actually a ZIP.

**Comment by Czuz** [comment]
> root@LibraryArchives ~ # cd /mnt/HD/HD_a2/Nas_Prog/
> root@LibraryArchives Nas_Prog # ls -la
> drwxrwxrwx 3 root root 4096 May 26 07:29 .
> drwxrwxrwx 12 root root 4096 May 25 02:45 ..
> drwxrwxrwx 3 root root 4096 May 26 07:30 _install

Hi. The output indicates that "bin" file has not been extracted and installed.

In order to manually perform this operations from shell you can:
1) unzip the bin file to `/mnt/HD/HD_a2/Nas_Prog/_install` 

2) initialize `UPLOAD` and `INSTALL` variables:
> UPLOAD="/mnt/HD/HD_a2/Nas_Prog/_install"
> INSTALL="/mnt/HD/HD_a2/Nas_Prog/mySync"

3) use the commands below to install / remove / start / stop / reinstall the app.

Install App:

> $UPLOAD/install.sh $UPLOAD $INSTALL
> $INSTALL/init.sh $INSTALL

Remove App:

> $INSTALL/stop.sh
> $INSTALL/clean.sh
> $INSTALL/remove.sh $INSTALL

Enable App:

> $INSTALL/start.sh

Disable App:

> $INSTALL/stop.sh

Reinstall App:

> $INSTALL/stop.sh
> $INSTALL/clean.sh
> $INSTALL/preinst.sh $INSTALL
> $INSTALL/remove.sh $INSTALL
> $UPLOAD/install.sh $UPLOAD $INSTALL
> $INSTALL/init.sh $INSTALL

Above instructions will install the scripts, but wouldn't register the app in the myCloud console. You will have to configure it also from OS level. Probably rebuilding the package from source would be better solution.

**Comment by Czuz** [comment]
@turnkit : try to use new release - I have rebuild it with newer version of mksapkg.

**Comment by Czuz** [comment]
@turnkit: Please let me know if rebuild helped. I would appreciate your feedback.
